"""initial schema

Revision ID: 1b990407c9a2
Revises: 
Create Date: 2026-09-30 16:28:59.214379
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '1b990407c9a2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_complete_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agendas',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeframe_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reminder_channel', sa.Enum('email', 'whatsapp', name='reminderchannel', native_enum=False, length=32), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generating', 'ready', 'active', 'completed', 'archived', 'cancelled', name='agendastatus', native_enum=False, length=32), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('perfect_run', sa.Boolean(), nullable=False),
    sa.Column('last_materialized_date', sa.Date(), nullable=True),
    sa.Column('last_closed_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_agendas_date_order'),
    sa.CheckConstraint('timeframe_days >= 1', name='ck_agendas_timeframe_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendas_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendas_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('agenda_drafts',
    sa.Column('agenda_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'needs_input', 'needs_review', 'approved', 'failed', name='draftstatus', native_enum=False, length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('clarifying_questions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('clarifying_answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('validation_issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('raw_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('repair_passes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agenda_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenda_drafts_agenda_id'), ['agenda_id'], unique=False)

    op.create_table('sub_agendas',
    sa.Column('agenda_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('expected_effort_minutes', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'done', 'missed', name='subagendastatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_user_edited', sa.Boolean(), nullable=False),
    sa.Column('todos_expanded', sa.Boolean(), nullable=False),
    sa.Column('completion_seq', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['agenda_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_id', 'day_index', name='uq_sub_agendas_agenda_day'),
    sa.UniqueConstraint('agenda_id', 'scheduled_date', name='uq_sub_agendas_agenda_date')
    )
    with op.batch_alter_table('sub_agendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_agendas_agenda_id'), ['agenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_agendas_scheduled_date'), ['scheduled_date'], unique=False)

    op.create_table('reminders',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agenda_id', sa.Uuid(), nullable=False),
    sa.Column('sub_agenda_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('daily', 'weekly_rollup', name='reminderkind', native_enum=False, length=32), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='reminderchannel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'claimed', 'sent', 'failed', 'skipped', name='reminderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('body_subject', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_agenda_id'], ['sub_agendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_reminders_dedupe')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_agenda_id'), ['agenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_user_id'), ['user_id'], unique=False)

    op.create_table('todos',
    sa.Column('sub_agenda_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agenda_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('agent', 'user', name='todosource', native_enum=False, length=32), nullable=False),
    sa.Column('completion_seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_agenda_id'], ['sub_agendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_agenda_id', 'position', name='uq_todos_day_position')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_agenda_id'), ['agenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_is_done'), ['is_done'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_sub_agenda_id'), ['sub_agenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_user_id'), ['user_id'], unique=False)

    op.create_table('points_ledger',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agenda_id', sa.Uuid(), nullable=True),
    sa.Column('sub_agenda_id', sa.Uuid(), nullable=True),
    sa.Column('todo_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Enum('task_completed', 'task_uncompleted', 'day_complete', 'day_missed', 'streak_bonus', 'agenda_complete', 'perfect_run', 'adjustment', name='ledgerreason', native_enum=False, length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sub_agenda_id'], ['sub_agendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_points_ledger_idempotency')
    )
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_ledger_occurred_on'), ['occurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_ledger_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_ledger_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_points_ledger_reason'))
        batch_op.drop_index(batch_op.f('ix_points_ledger_occurred_on'))

    op.drop_table('points_ledger')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_user_id'))
        batch_op.drop_index(batch_op.f('ix_todos_sub_agenda_id'))
        batch_op.drop_index(batch_op.f('ix_todos_is_done'))
        batch_op.drop_index(batch_op.f('ix_todos_agenda_id'))

    op.drop_table('todos')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_agenda_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('sub_agendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_agendas_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_sub_agendas_agenda_id'))

    op.drop_table('sub_agendas')
    with op.batch_alter_table('agenda_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenda_drafts_agenda_id'))

    op.drop_table('agenda_drafts')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendas_user_id'))
        batch_op.drop_index(batch_op.f('ix_agendas_status'))
        batch_op.drop_index(batch_op.f('ix_agendas_end_date'))

    op.drop_table('agendas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
